export const WILAYAS = [
  { code: 1, name_ar: "أدرار", name_en: "Adrar", unsupported: true },
  { code: 2, name_ar: "الشلف", name_en: "Chlef" },
  { code: 3, name_ar: "الأغواط", name_en: "Laghouat", unsupported: true },
  { code: 4, name_ar: "أم البواقي", name_en: "Oum El Bouaghi" },
  { code: 5, name_ar: "باتنة", name_en: "Batna" },
  { code: 6, name_ar: "بجاية", name_en: "Bejaia" },
  { code: 7, name_ar: "بسكرة", name_en: "Biskra", unsupported: true },
  { code: 8, name_ar: "بشار", name_en: "Bechar", unsupported: true },
  { code: 9, name_ar: "البليدة", name_en: "Blida" },
  { code: 10, name_ar: "البويرة", name_en: "Bouira" },
  { code: 11, name_ar: "تمنراست", name_en: "Tamanrasset", unsupported: true },
  { code: 12, name_ar: "تبسة", name_en: "Tebessa" },
  { code: 13, name_ar: "تلمسان", name_en: "Tlemcen" },
  { code: 14, name_ar: "تيارت", name_en: "Tiaret" },
  { code: 15, name_ar: "تيزي وزو", name_en: "Tizi Ouzou" },
  { code: 16, name_ar: "الجزائر", name_en: "Alger" },
  { code: 17, name_ar: "الجلفة", name_en: "Djelfa", unsupported: true },
  { code: 18, name_ar: "جيجل", name_en: "Jijel" },
  { code: 19, name_ar: "سطيف", name_en: "Setif" },
  { code: 20, name_ar: "سعيدة", name_en: "Saida", unsupported: true },
  { code: 21, name_ar: "سكيكدة", name_en: "Skikda" },
  { code: 22, name_ar: "سيدي بلعباس", name_en: "Sidi Bel Abbes" },
  { code: 23, name_ar: "عنابة", name_en: "Annaba" },
  { code: 24, name_ar: "قالمة", name_en: "Guelma" },
  { code: 25, name_ar: "قسنطينة", name_en: "Constantine" },
  { code: 26, name_ar: "المدية", name_en: "Medea" },
  { code: 27, name_ar: "مستغانم", name_en: "Mostaganem" },
  { code: 28, name_ar: "المسيلة", name_en: "M'Sila" },
  { code: 29, name_ar: "معسكر", name_en: "Mascara" },
  { code: 30, name_ar: "ورقلة", name_en: "Ouargla", unsupported: true },
  { code: 31, name_ar: "وهران", name_en: "Oran" },
  { code: 32, name_ar: "البيض", name_en: "El Bayadh", unsupported: true },
  { code: 33, name_ar: "إليزي", name_en: "Illizi", unsupported: true },
  { code: 34, name_ar: "برج بوعريريج", name_en: "Bordj Bou Arreridj" },
  { code: 35, name_ar: "بومرداس", name_en: "Boumerdes" },
  { code: 36, name_ar: "الطارف", name_en: "El Tarf", unsupported: true },
  { code: 37, name_ar: "تندوف", name_en: "Tindouf", unsupported: true },
  { code: 38, name_ar: "تيسمسيلت", name_en: "Tissemsilt" },
  { code: 39, name_ar: "الوادي", name_en: "El Oued", unsupported: true },
  { code: 40, name_ar: "خنشلة", name_en: "Khenchela", unsupported: true },
  { code: 41, name_ar: "سوق أهراس", name_en: "Souk Ahras" },
  { code: 42, name_ar: "تيبازة", name_en: "Tipaza" },
  { code: 43, name_ar: "ميلة", name_en: "Mila" },
  { code: 44, name_ar: "عين الدفلى", name_en: "Ain Defla" },
  { code: 45, name_ar: "النعامة", name_en: "Naama", unsupported: true },
  { code: 46, name_ar: "عين تيموشنت", name_en: "Ain Temouchent", unsupported: true },
  { code: 47, name_ar: "غرداية", name_en: "Ghardaia", unsupported: true },
  { code: 48, name_ar: "غليزان", name_en: "Relizane" },
  { code: 49, name_ar: "تيميمون", name_en: "Timimoun", unsupported: true },
  { code: 50, name_ar: "برج باجي مختار", name_en: "Bordj Badji Mokhtar", unsupported: true },
  { code: 51, name_ar: "أولاد جلال", name_en: "Ouled Djellal", unsupported: true },
  { code: 52, name_ar: "بني عباس", name_en: "Beni Abbes", unsupported: true },
  { code: 53, name_ar: "عين صالح", name_en: "Ain Salah", unsupported: true },
  { code: 54, name_ar: "عين قزام", name_en: "Ain Guezzam", unsupported: true },
  { code: 55, name_ar: "توقرت", name_en: "Touggourt", unsupported: true },
  { code: 56, name_ar: "جانت", name_en: "Djanet", unsupported: true },
  { code: 57, name_ar: "المغير", name_en: "El M'Ghair", unsupported: true },
  { code: 58, name_ar: "المنيعة", name_en: "El Meniaa", unsupported: true }
];
